---
kind: ingress
apiVersion: v1
metadata:
  name: spring-boot-hello
  namespace: flux
spec:
  type: ingress
  selector:
    app: spring-boot-hello
  ports:
    - host : welcome.zz8jpq6ohou4p5plbkic.apps.klusternetes.com
      name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
