---
kind: ingress
apiVersion: v1
metadata:
  name: spring-boot-hello
  namespace: flux
spec:
  type: ingress
  selector:
    app: spring-boot-hello
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
